name: lifter
description: "A weight lifting progression app with intelligent progression algorithms."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.6
  bloc_test: ^9.1.7
  
  # Routing
  go_router: ^14.6.2
  
  # Dependency Injection
  get_it: ^7.7.0
  
  # Local Storage (SQL)
  drift: ^2.17.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Code Generation
  drift_dev: ^2.17.0
  build_runner: ^2.4.13
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  
  # Utilities
  logging: ^1.2.0
  collection: ^1.18.0
  
  # UI
  cupertino_icons: ^1.0.8
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code Generation
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  
  # Testing
  mockito: ^5.4.4
  clock: ^1.1.1
  fake_async: ^1.3.2

flutter:
  uses-material-design: true
